// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Syamil Maulod",
            "url": "https://bearylogical.net",
            "email": "syamil@bearylogical.net"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/budget": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "List expenditure",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "budget"
                ],
                "summary": "List expenditure",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Value Year",
                        "name": "valueYear",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Value Type",
                        "name": "valueType",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.Expenditure"
                            }
                        }
                    }
                }
            }
        },
        "/budget/opts": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get budget options",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "budget"
                ],
                "summary": "Get budget options",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.BudgetOpts"
                        }
                    }
                }
            }
        },
        "/budget/{ministry_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "List expenditure by ministry",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "budget"
                ],
                "summary": "List expenditure by ministry",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Ministry ID",
                        "name": "ministry_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.Expenditure"
                            }
                        }
                    }
                }
            }
        },
        "/budget/{ministry_id}/documents": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "List documents by ministry ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "documents"
                ],
                "summary": "List documents by ministry ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Ministry ID",
                        "name": "ministry_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.Document"
                            }
                        }
                    }
                }
            }
        },
        "/budget/{ministry_id}/programmes": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get programme expenditure by ministry ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "budget"
                ],
                "summary": "Get programme expenditure by ministry ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Ministry ID",
                        "name": "ministry_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.ProgrammeExpenditure"
                            }
                        }
                    }
                }
            }
        },
        "/budget/{ministry_id}/projects": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "List project expenditure by ministry ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "budget"
                ],
                "summary": "List project expenditure by ministry ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Ministry ID",
                        "name": "ministry_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.ProjectExpenditure"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check if the API is up and running",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "status: UP",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/ministries": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all ministries",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ministries"
                ],
                "summary": "List all ministries",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.Ministry"
                            }
                        }
                    }
                }
            }
        },
        "/ministries/{ministry_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a ministry by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ministries"
                ],
                "summary": "Get a ministry by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Ministry ID",
                        "name": "ministry_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.Ministry"
                        }
                    }
                }
            }
        },
        "/personnel": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "List top N personnel by ministry ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "personnel"
                ],
                "summary": "List top N personnel by ministry ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Ministry ID",
                        "name": "ministryID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Top N",
                        "name": "topN",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Start Year",
                        "name": "startYear",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.Personnel"
                            }
                        }
                    }
                }
            }
        },
        "/projects": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get project expenditure by query",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "budget"
                ],
                "summary": "Get project expenditure by query",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Query",
                        "name": "query",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.ProjectExpenditure"
                            }
                        }
                    }
                }
            }
        },
        "/projects/{project_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get project expenditure by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "budget"
                ],
                "summary": "Get project expenditure by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ProjectExpenditure"
                        }
                    }
                }
            }
        },
        "/sgdi/{ministry_id}/links": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "List SGDI links by ministry ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sgdi"
                ],
                "summary": "List SGDI links by ministry ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Ministry ID",
                        "name": "ministry_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.SGDILink"
                            }
                        }
                    }
                }
            }
        },
        "/v2/budget": {
            "get": {
                "description": "Get ministry data by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ministries"
                ],
                "summary": "Get ministry data by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Ministry ID",
                        "name": "ministryID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Top N",
                        "name": "topN",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Start Year",
                        "name": "startYear",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.Ministry"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "types.BudgetOpts": {
            "type": "object",
            "properties": {
                "value_type": {
                    "type": "string"
                },
                "value_year": {
                    "type": "integer"
                }
            }
        },
        "types.Document": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "document_id": {
                    "type": "integer"
                },
                "document_name": {
                    "type": "string"
                },
                "document_path": {
                    "type": "string"
                },
                "md5_hash": {
                    "type": "string"
                },
                "ministry": {
                    "type": "string"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "types.Expenditure": {
            "type": "object",
            "properties": {
                "ministry_id": {
                    "type": "string"
                },
                "value_amount": {
                    "type": "number"
                },
                "value_type": {
                    "type": "string"
                },
                "value_year": {
                    "type": "integer"
                }
            }
        },
        "types.Ministry": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "types.Personnel": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "personnel_type": {
                    "type": "string"
                },
                "value_amount": {
                    "type": "integer"
                },
                "value_type": {
                    "type": "string"
                },
                "value_year": {
                    "type": "integer"
                }
            }
        },
        "types.ProgrammeExpenditure": {
            "type": "object",
            "properties": {
                "document_id": {
                    "type": "integer"
                },
                "document_year": {
                    "type": "integer"
                },
                "expenditure_id": {
                    "type": "integer"
                },
                "ministry": {
                    "type": "string"
                },
                "ministry_id": {
                    "type": "integer"
                },
                "programme_id": {
                    "type": "integer"
                },
                "programme_title": {
                    "type": "string"
                },
                "value_amount": {
                    "type": "number"
                },
                "value_code": {
                    "type": "string"
                },
                "value_name": {
                    "type": "string"
                },
                "value_year": {
                    "type": "integer"
                }
            }
        },
        "types.ProjectExpenditure": {
            "type": "object",
            "properties": {
                "document_id": {
                    "type": "integer"
                },
                "document_year": {
                    "type": "integer"
                },
                "expenditure_id": {
                    "type": "integer"
                },
                "ministry": {
                    "type": "string"
                },
                "ministry_id": {
                    "type": "integer"
                },
                "parent_header": {
                    "type": "string"
                },
                "project_id": {
                    "type": "integer"
                },
                "project_title": {
                    "type": "string"
                },
                "value_amount": {
                    "type": "number"
                },
                "value_type": {
                    "type": "string"
                },
                "value_year": {
                    "type": "integer"
                }
            }
        },
        "types.SGDILink": {
            "type": "object",
            "properties": {
                "child_name": {
                    "type": "string"
                },
                "child_url": {
                    "type": "string"
                },
                "parent_name": {
                    "type": "string"
                },
                "parent_url": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "Gahmen Budget API",
	Description:      "Gahmen Budget API provides access to Singapore's government budget data.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
